import {
  IconBell,
  IconChartBar,
  IconUsers,
  IconGridScan,
  IconSettings,
  IconFiles,
  IconHeartHandshake,
  IconMessage,
  IconPhoneCall,
  IconCheckupList,
} from '@tabler/icons-react';

export const MenuGroups = {
  communication: {
    id: 'category_communication',
    label: 'Общение',
    labelKey: 'common:menu.communication',
    Icon: IconMessage,
    order: 10,
  },
  stock: {
    id: 'category_stock',
    label: 'Склад',
    labelKey: 'common:menu.stock',
    Icon: IconGridScan,
    order: 20,
    visibleForRoles: ['stock_user', 'stock_manager', 'stock_admin'] as string[],
  },
  contacts: {
    id: 'category_contacts',
    label: 'Партнеры',
    labelKey: 'common:menu.contacts',
    Icon: IconUsers,
    order: 30,
    // visibleForRoles: [
    // 'partner_user',
    // 'partner_manager',
    // 'partner_admin',
    // ] as string[],
  },
  crm: {
    id: 'category_crm',
    label: 'CRM',
    labelKey: 'common:menu.crm',
    Icon: IconHeartHandshake,
    order: 40,
    visibleForRoles: ['crm_user', 'crm_manager', 'crm_admin'] as string[],
  },
  projects: {
    id: 'category_projects',
    label: 'Проекты',
    labelKey: 'common:menu.projects',
    Icon: IconCheckupList,
    order: 45,
    visibleForRoles: [
      'project_user',
      'project_manager',
      'project_admin',
    ] as string[],
  },
  activity: {
    id: 'category_activity',
    label: 'Активности',
    labelKey: 'common:menu.activity',
    Icon: IconBell,
    order: 45,
  },
  sales: {
    id: 'category_sales',
    label: 'Продажи',
    labelKey: 'common:menu.sales',
    Icon: IconChartBar,
    order: 50,
    visibleForRoles: ['sale_user', 'sale_manager', 'sale_admin'] as string[],
  },
  telephony: {
    id: 'category_telephony',
    label: 'Телефония',
    labelKey: 'common:menu.telephony',
    Icon: IconPhoneCall,
    order: 60,
    visibleForRoles: [
      'telephony_user',
      'telephony_manager',
      'telephony_admin',
    ] as string[],
  },
  files: {
    id: 'category_files',
    label: 'Файлы',
    labelKey: 'common:menu.files',
    Icon: IconFiles,
    order: 70,
  },
  settings: {
    id: 'category_settings',
    label: 'Настройки',
    labelKey: 'common:menu.settings',
    Icon: IconSettings,
    order: 90,
    visibleForRoles: ['system_admin'] as string[],
  },
} as const;

export type MenuGroup = (typeof MenuGroups)[keyof typeof MenuGroups];
