# ============================================================
#  FARA CRM - logging configuration
#  uvicorn: --log-config ./backend/base/system/logger/logging.yaml
# ============================================================

version: 1
disable_existing_loggers: false

formatters:
  default:
    format: "%(asctime)s  %(levelname)-8s  %(name)s | %(message)s"
    datefmt: "%H:%M:%S"

  access:
    format: "%(asctime)s  %(levelname)-8s  %(message)s"
    datefmt: "%H:%M:%S"

  # Colored [FARA CRM] / [FARA SYSTEM] / [FARA CRON] tags
  fara:
    (): backend.base.system.logger.colored.FaraFormatter
    format: "%(asctime)s  %(levelname)-8s  %(name)s | %(message)s"
    datefmt: "%H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    stream: ext://sys.stdout
    formatter: default

  access_console:
    class: logging.StreamHandler
    stream: ext://sys.stdout
    formatter: access

  fara_console:
    class: logging.StreamHandler
    stream: ext://sys.stdout
    formatter: fara

loggers:
  # -- Uvicorn -----------------------------------------------
  uvicorn:
    level: INFO
    handlers: [console]
    propagate: false

  # -- Database / ORM ----------------------------------------
  dotorm:
    level: WARNING
    handlers: [console]
    propagate: false

  asyncpg:
    level: WARNING
    handlers: [console]
    propagate: false

  # -- Python internals --------------------------------------
  asyncio:
    level: WARNING
    handlers: [console]
    propagate: false

  # -- Application code --------------------------------------
  backend.base.system:
    level: INFO
    handlers: [fara_console]
    propagate: false

  backend.base.crm:
    level: INFO
    handlers: [fara_console]
    propagate: false

  cron:
    level: INFO
    handlers: [fara_console]
    propagate: false

root:
  level: WARNING
  handlers: [console]
